name: Build readme

on:
  push:
    paths:
      - readme-src.adoc
    branches:
      - '**'

jobs:
  build:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Install asciidoctor-reducer
        run: sudo gem install asciidoctor-reducer --pre

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Reduce readme
        run: asciidoctor-reducer -o README.adoc readme-src.adoc

      - name: Commit readme
        uses: EndBug/add-and-commit@v8
